export interface Feature {
  id: number;
  name: string;
  description: string;
  domain: string;
}

export const FEATURES: Feature[] = [
  // Domain 1: POS & Unified Sales Terminal (1-60)
  { id: 1, name: "High-Density Product Grid", description: "4-column layout for Desktop/Tablet", domain: "POS & Sales" },
  { id: 2, name: "Category Quick-Tabs", description: "Instant switching (Phones, Repairs, Accessories)", domain: "POS & Sales" },
  { id: 3, name: "Elastic Search Bar", description: "Instant results by SKU, Name, IMEI", domain: "POS & Sales" },
  { id: 4, name: "Hardware Scanner Sync", description: "Native HID/USB Barcode & Camera integration", domain: "POS & Sales" },
  { id: 5, name: "Forced IMEI/Serial Validation", description: "Blocks cart if 15-digit serial missing for phones", domain: "POS & Sales" },
  { id: 6, name: "Duplicate IMEI Prevention", description: "Real-time DB check to prevent double-selling a serial", domain: "POS & Sales" },
  { id: 7, name: "Dynamic Product Bundling", description: "1-click “Kits” with auto-deduction", domain: "POS & Sales" },
  { id: 8, name: "Wholesale vs. Retail Toggle", description: "Instant price-book switch for B2B", domain: "POS & Sales" },
  { id: 9, name: "Flash Sale Scheduler", description: "Pre-programmed start/end times for discounts", domain: "POS & Sales" },
  { id: 10, name: "Store Credit Wallet", description: "Digital balance for returns", domain: "POS & Sales" },
  { id: 11, name: "Partial/Deposit Payments", description: "Track deposits for “On-Hold” items", domain: "POS & Sales" },
  { id: 12, name: "Multi-Payment Split", description: "Combine Cash + K-Net + Credit Card", domain: "POS & Sales" },
  { id: 13, name: "Line-Item Discounts", description: "Percentage or fixed KD per product", domain: "POS & Sales" },
  { id: 14, name: "Global Cart Discounts", description: "Applied to final subtotal", domain: "POS & Sales" },
  { id: 15, name: "Tax-Inclusive/Exclusive Toggle", description: "Switch VAT/GST display", domain: "POS & Sales" },
  { id: 16, name: "Hold/Resume Cart", description: "Multiple active customer sessions", domain: "POS & Sales" },
  { id: 17, name: "Quick Customer Add", description: "Create profile via mobile number (5 seconds)", domain: "POS & Sales" },
  { id: 18, name: "Loyalty Accrual Logic", description: "Automated points based on KD spent", domain: "POS & Sales" },
  { id: 19, name: "Loyalty Redemption", description: "Use points as payment method", domain: "POS & Sales" },
  { id: 20, name: "Gift Card Ledger", description: "Issue and track alphanumeric gift codes", domain: "POS & Sales" },
  { id: 21, name: "Bilingual Receipts", description: "EN/AR layout for thermal printers", domain: "POS & Sales" },
  { id: 22, name: "QR Code Generation", description: "For tax invoice validation", domain: "POS & Sales" },
  { id: 23, name: "Receipt Reprint History", description: "Access last 10,000 receipts", domain: "POS & Sales" },
  { id: 24, name: "WhatsApp Receipt Share", description: "Generate wa.me link with PDF invoice", domain: "POS & Sales" },
  { id: 25, name: "A4 Invoice PDF", description: "Professional layout for B2B", domain: "POS & Sales" },
  { id: 26, name: "Sales Agent Tagging", description: "Attribute sales to staff for commission", domain: "POS & Sales" },
  { id: 27, name: "Price Overrides", description: "Manager PIN required", domain: "POS & Sales" },
  { id: 28, name: "Item Deletion Audit", description: "Log every item removed from cart", domain: "POS & Sales" },
  { id: 29, name: "Voided Sale Record", description: "Archive cancelled sales with reason codes", domain: "POS & Sales" },
  { id: 30, name: "Cash Drawer Kick", description: "Hardware trigger to open drawer", domain: "POS & Sales" },
  { id: 31, name: "Offline-First Mode", description: "Local transaction queue for internet outages", domain: "POS & Sales" },
  { id: 32, name: "Auto-Sync Engine", description: "Upload offline sales when online", domain: "POS & Sales" },
  { id: 33, name: "Customer-Facing Display", description: "Sync cart data to secondary monitor", domain: "POS & Sales" },
  { id: 34, name: "Promotional Coupons", description: "Validate alphanumeric discount codes", domain: "POS & Sales" },
  { id: 35, name: "Refund Period Validator", description: "Block returns after X-day limit", domain: "POS & Sales" },
  { id: 36, name: "Custom Service Fees", description: "Manual labour entry", domain: "POS & Sales" },
  { id: 37, name: "BOGO Logic", description: "Buy-one-get-one discount detection", domain: "POS & Sales" },
  { id: 38, name: "Gift Wrapping Logic", description: "Add packaging service fees", domain: "POS & Sales" },
  { id: 39, name: "Sales Tax Auto-Calc", description: "Real-time tax by region", domain: "POS & Sales" },
  { id: 40, name: "Multi-Currency Display", description: "Show total in INR/USD for tourists", domain: "POS & Sales" },

  // Domain 2: Deep-Tech Repair Hub (61-120)
  { id: 61, name: "Job Card Intake", description: "Capture IMEI, Color, Passcode", domain: "Repairs" },
  { id: 62, name: "Fault Diagnostic Tree", description: "Pre-defined issues list", domain: "Repairs" },
  { id: 63, name: "Visual Damage Mapping", description: "Draw cracks/scratches on device UI", domain: "Repairs" },
  { id: 64, name: "Pre-Repair Video/Photo", description: "Attach visual proof to job card", domain: "Repairs" },
  { id: 65, name: "Technician Bench Assignment", description: "Map job to specific staff ID", domain: "Repairs" },
  { id: 66, name: "SLA Countdown Timer", description: "1-hour express repair monitor", domain: "Repairs" },
  { id: 67, name: "Status Pipeline", description: "Diagnosing → Parts Ordered → Fixing → QC", domain: "Repairs" },
  { id: 68, name: "Internal Bench Notes", description: "Private technical logs", domain: "Repairs" },
  { id: 69, name: "Spare Parts Auto-Deduction", description: "Trigger inventory drop on completion", domain: "Repairs" },
  { id: 70, name: "Parts Request Flow", description: "Tech → Inventory notification", domain: "Repairs" },
  { id: 71, name: "20-Point QC Checklist", description: "FaceID, Mic, Camera, etc.", domain: "Repairs" },
  { id: 72, name: "Digital Signature", description: "Customer sign on tablet", domain: "Repairs" },
  { id: 73, name: "Warranty Sticker Gen", description: "Print unique date-coded stickers", domain: "Repairs" },
  { id: 74, name: "WhatsApp Status Bot", description: "Auto-alert “Ready for Pickup”", domain: "Repairs" },
  { id: 75, name: "Used Device Buy-Back", description: "Identity scanning, automated grading (A/B/C)", domain: "Repairs" },

  // Domain 3: Inventory & Supply Chain (121-180)
  { id: 121, name: "Multi-Store Matrix View", description: "Real-time stock across all branches", domain: "Inventory" },
  { id: 122, name: "Inter-Store Transfer Request", description: "Formal request flow between managers", domain: "Inventory" },
  { id: 123, name: "In-Transit Tracking", description: "Status of moving stock", domain: "Inventory" },
  { id: 124, name: "Transfer Approval Workflow", description: "Request → Ship → Receive chain", domain: "Inventory" },
  { id: 125, name: "Low Stock Dashboard", description: "Visual triggers for critical items", domain: "Inventory" },
  { id: 126, name: "Predictive Re-order Alerts", description: "Suggestions based on 30-day sales velocity", domain: "Inventory" },
  { id: 127, name: "Purchase Order (PO) Drafting", description: "Professional orders to vendors", domain: "Inventory" },
  { id: 128, name: "Landed Cost Calculator", description: "Add Customs/Shipping/Mandoob fees", domain: "Inventory" },
  { id: 129, name: "Supplier RMA Tracking", description: "Defective parts sent back for credit", domain: "Inventory" },
  { id: 130, name: "“Blind” Stock Counting", description: "Staff count without system totals", domain: "Inventory" },

  // Domain 4: Governance, Security & HR (181-240)
  { id: 181, name: "Master Audit Trail", description: "Chronological log of every click/edit", domain: "Governance" },
  { id: 182, name: "Price Edit History", description: "Track who changed a price and why", domain: "Governance" },
  { id: 183, name: "Void/Delete Audit", description: "Detailed report on cancelled transactions", domain: "Governance" },
  { id: 184, name: "Role-Based Sidebar Filtering", description: "Dynamically hide features by permission", domain: "Governance" },
  { id: 185, name: "Feature Toggle Board", description: "Super Admin switches for all 300 features", domain: "Governance" },
  { id: 186, name: "IP Whitelisting", description: "Restrict admin access to shop Wi-Fi", domain: "Governance" },
  { id: 187, name: "Geofencing Login", description: "Staff only log in while at GPS location", domain: "Governance" },
  { id: 188, name: "Staff Attendance", description: "Clock-in/out with location verification", domain: "Governance" },
  { id: 189, name: "Automated Commission Math", description: "Sales + Repair bonuses per employee", domain: "Governance" },
  { id: 190, name: "Daily Z-Report", description: "Final financial end-of-day summary", domain: "Governance" },
  { id: 191, name: "Mid-Shift X-Report", description: "Snapshot without closing", domain: "Governance" },
  { id: 192, name: "Profit & Loss Dashboard", description: "Daily/Monthly gross margin view", domain: "Governance" },
  { id: 193, name: "Expense Tracker", description: "Log Rent/Tea/Utilities/Mandoob fees", domain: "Governance" },
  { id: 194, name: "VAT/Tax Export", description: "Government-ready CSV for filing", domain: "Governance" },
  { id: 195, name: "Role Template Creator", description: "Presets for “Cashier”, “Manager”, etc.", domain: "Governance" },

  // Domain 7: New Enterprise Features (316-350)
  { id: 316, name: "Batch Intake Buffer", description: "Scan-to-bucket with exceptions tab; async commit; Web Worker validation.", domain: "Enterprise" },
  { id: 317, name: "PITR Restore Slider", description: "Time-travel recovery for specific collections (products, customers, prices).", domain: "Enterprise" },
  { id: 318, name: "Blind Cycle Count Toggle", description: "Zero-visibility counting for audit integrity; manager sees discrepancy only.", domain: "Enterprise" },
  { id: 319, name: "API Circuit Breaker Panel", description: "Per-API trip switch (WhatsApp, KNET, GSMA); auto-trip after 3 failures.", domain: "Enterprise" },
  { id: 320, name: "Pro-forma Quote Mode", description: "B2B quote → invoice flow; quote PDF with expiry date.", domain: "Enterprise" },
  { id: 321, name: "Store Opening Checklist", description: "Digital checklist (lights, cash float, printer) before first sale.", domain: "Enterprise" },
  { id: 322, name: "Customer Wishlist / Back in Stock Alert", description: "Customer requests notification when item returns in stock.", domain: "Enterprise" },
  { id: 323, name: "Technician Certification Expiry Tracker", description: "Alerts manager when Apple/GSX certification expires.", domain: "Enterprise" },
  { id: 324, name: "Inter-Store Loan (Temporary)", description: "Loan with return date; auto-reminder; separate from permanent transfer.", domain: "Enterprise" },
  { id: 325, name: "POS Screen Auto-Lock", description: "Idle timeout (configurable) with PIN resume.", domain: "Enterprise" },
  { id: 326, name: "Batch Job Manager UI", description: "Global drawer (Ctrl+J) to track async jobs (exports, imports, label printing).", domain: "Enterprise" },
  { id: 327, name: "ZPL Print Engine", description: "Direct-to-printer ZPL commands; 10x faster than PDF.", domain: "Enterprise" },
  { id: 328, name: "Virtual Scrolling", description: "react-window for product list, repair history, audit log.", domain: "Enterprise" },
  { id: 329, name: "Conflict Resolution UI", description: "When offline sale conflicts with online, manager decides: cancel or backorder.", domain: "Enterprise" },
  { id: 330, name: "Manager PIN Override", description: "4-digit PIN required for void, refund >threshold, no-sale drawer open.", domain: "Enterprise" },
  { id: 331, name: "Fast-Switch User PIN Overlay", description: "Change active cashier without full logout; 4-digit PIN.", domain: "Enterprise" },
  { id: 332, name: "Carrier Commission Clawback Ledger", description: "Track SIM plan commissions; auto-deduct if customer cancels early.", domain: "Enterprise" },
  { id: 333, name: "RMA to Vendor Flow", description: "Defective parts return; track credit note; separate from customer returns.", domain: "Enterprise" },
  { id: 334, name: "API Kill Switch (Global)", description: "Emergency disable all external APIs; system switches to manual mode.", domain: "Enterprise" },
  { id: 335, name: "Session Invalidation by Branch", description: "Force logout all users in a specific store (security breach response).", domain: "Enterprise" },
  { id: 336, name: "Post-Scan Reconciliation UI", description: "After bulk scan, show expected vs scanned; highlight missing units.", domain: "Enterprise" },
  { id: 337, name: "IMEI Range Auto-Generation", description: "Enter first and last IMEI; system creates all in-between.", domain: "Enterprise" },
  { id: 338, name: "Batch Label Spooler", description: "Send 100+ ZPL label commands to printer in one job.", domain: "Enterprise" },
  { id: 339, name: "Asynchronous Export", description: "Export large data (e.g., 50k invoices) in background; notify via WhatsApp when ready.", domain: "Enterprise" },
  { id: 340, name: "Database Self-Heal Dashboard", description: "Nightly integrity check; find orphaned records; one-click repair.", domain: "Enterprise" },
  { id: 341, name: "Three-Tier Backup Strategy UI", description: "Manage hot (real-time), warm (daily regional), cold (immutable WORM) backups.", domain: "Enterprise" },
  { id: 342, name: "Read-Replica Routing", description: "Cockpit queries automatically use read replica to avoid POS lag.", domain: "Enterprise" },
  { id: 343, name: "Request Coalescing", description: "Batch identical API requests (e.g., 50 terminals asking for exchange rate → 1 call).", domain: "Enterprise" },
  { id: 344, name: "Web Worker IMEI Validation", description: "Offload IMEI regex and duplicate checks to background thread.", domain: "Enterprise" },
  { id: 345, name: "IndexedDB Product Cache", description: "Store product catalog locally; only sync delta changes.", domain: "Enterprise" },
  { id: 346, name: "Bulk SKU Generation", description: "Auto-create SKUs for a range of IMEIs (e.g., IP15PM-{IMEI_last4}).", domain: "Enterprise" },
  { id: 347, name: "Customer Account Freeze Toggle", description: "Temporarily block a customer from making purchases (fraud investigation).", domain: "Enterprise" },
  { id: 348, name: "Repair Part Substitution Log", description: "Record when technician uses different part than quoted; requires manager approval.", domain: "Enterprise" },
  { id: 349, name: "Cash Drawer Soft Count", description: "Mid-shift cash estimate without closing drawer; logs expected range.", domain: "Enterprise" },
  { id: 350, name: "Supplier MOQ Alert", description: "Warn during PO creation if quantity below supplier MOQ.", domain: "Enterprise" },
];
