export interface Feature {
  id: number;
  name: string;
  description: string;
  domain: string;
}

export const FEATURES: Feature[] = [
  // Domain 1: POS & Unified Sales Terminal (1-60)
  { id: 1, name: "High‑Density Product Grid", description: "4‑column layout for Desktop/Tablet", domain: "POS & Sales" },
  { id: 2, name: "Category Quick‑Tabs", description: "Instant switching (Phones, Repairs, Accessories)", domain: "POS & Sales" },
  { id: 3, name: "Elastic Search Bar", description: "Instant results by SKU, Name, IMEI", domain: "POS & Sales" },
  { id: 4, name: "Hardware Scanner Sync", description: "Native HID/USB Barcode & Camera integration", domain: "POS & Sales" },
  { id: 5, name: "Forced IMEI/Serial Validation", description: "Blocks cart if 15‑digit serial missing for phones", domain: "POS & Sales" },
  { id: 6, name: "Duplicate IMEI Prevention", description: "Real‑time DB check to prevent double‑selling a serial", domain: "POS & Sales" },
  { id: 7, name: "Dynamic Product Bundling", description: "1‑click “Kits” with auto‑deduction", domain: "POS & Sales" },
  { id: 8, name: "Wholesale vs. Retail Toggle", description: "Instant price‑book switch for B2B", domain: "POS & Sales" },
  { id: 9, name: "Flash Sale Scheduler", description: "Pre‑programmed start/end times for discounts", domain: "POS & Sales" },
  { id: 10, name: "Store Credit Wallet", description: "Digital balance for returns", domain: "POS & Sales" },
  { id: 11, name: "Partial/Deposit Payments", description: "Track deposits for “On‑Hold” items", domain: "POS & Sales" },
  { id: 12, name: "Multi‑Payment Split", description: "Combine Cash + K‑Net + Credit Card", domain: "POS & Sales" },
  { id: 13, name: "Line‑Item Discounts", description: "Percentage or fixed KD per product", domain: "POS & Sales" },
  { id: 14, name: "Global Cart Discounts", description: "Applied to final subtotal", domain: "POS & Sales" },
  { id: 15, name: "Tax‑Inclusive/Exclusive Toggle", description: "Switch VAT/GST display", domain: "POS & Sales" },
  { id: 16, name: "Hold/Resume Cart", description: "Multiple active customer sessions", domain: "POS & Sales" },
  { id: 17, name: "Quick Customer Add", description: "Create profile via mobile number (5 seconds)", domain: "POS & Sales" },
  { id: 18, name: "Loyalty Accrual Logic", description: "Automated points based on KD spent", domain: "POS & Sales" },
  { id: 19, name: "Loyalty Redemption", description: "Use points as payment method", domain: "POS & Sales" },
  { id: 20, name: "Gift Card Ledger", description: "Issue and track alphanumeric gift codes", domain: "POS & Sales" },
  { id: 21, name: "Bilingual Receipts", description: "EN/AR layout for thermal printers", domain: "POS & Sales" },
  { id: 22, name: "QR Code Generation", description: "For tax invoice validation", domain: "POS & Sales" },
  { id: 23, name: "Receipt Reprint History", description: "Access last 10,000 receipts", domain: "POS & Sales" },
  { id: 24, name: "WhatsApp Receipt Share", description: "Generate wa.me link with PDF invoice", domain: "POS & Sales" },
  { id: 25, name: "A4 Invoice PDF", description: "Professional layout for B2B", domain: "POS & Sales" },
  { id: 26, name: "Sales Agent Tagging", description: "Attribute sales to staff for commission", domain: "POS & Sales" },
  { id: 27, name: "Price Overrides", description: "Manager PIN required", domain: "POS & Sales" },
  { id: 28, name: "Item Deletion Audit", description: "Log every item removed from cart", domain: "POS & Sales" },
  { id: 29, name: "Voided Sale Record", description: "Archive cancelled sales with reason codes", domain: "POS & Sales" },
  { id: 30, name: "Cash Drawer Kick", description: "Hardware trigger to open drawer", domain: "POS & Sales" },
  { id: 31, name: "Offline‑First Mode", description: "Local transaction queue for internet outages", domain: "POS & Sales" },
  { id: 32, name: "Auto‑Sync Engine", description: "Upload offline sales when online", domain: "POS & Sales" },
  { id: 33, name: "Customer‑Facing Display", description: "Sync cart data to secondary monitor", domain: "POS & Sales" },
  { id: 34, name: "Promotional Coupons", description: "Validate alphanumeric discount codes", domain: "POS & Sales" },
  { id: 35, name: "Refund Period Validator", description: "Block returns after X‑day limit", domain: "POS & Sales" },
  { id: 36, name: "Custom Service Fees", description: "Manual labour entry", domain: "POS & Sales" },
  { id: 37, name: "BOGO Logic", description: "Buy‑one‑get‑one discount detection", domain: "POS & Sales" },
  { id: 38, name: "Gift Wrapping Logic", description: "Add packaging service fees", domain: "POS & Sales" },
  { id: 39, name: "Sales Tax Auto‑Calc", description: "Real‑time tax by region", domain: "POS & Sales" },
  { id: 40, name: "Multi‑Currency Display", description: "Show total in INR/USD for tourists", domain: "POS & Sales" },
  { id: 41, name: "Daily Sales Goal Tracker", description: "Progress bar in POS", domain: "POS & Sales" },
  { id: 42, name: "Inventory Reserve", description: "Hold item for 24 hours", domain: "POS & Sales" },
  { id: 43, name: "Employee Purchase Price", description: "Auto‑apply staff discount", domain: "POS & Sales" },
  { id: 44, name: "Quick‑Change Calculator", description: "Suggest cash denominations", domain: "POS & Sales" },
  { id: 45, name: "Rounding Logic", description: "Automated rounding for cash", domain: "POS & Sales" },
  { id: 46, name: "Customer Debt Notification", description: "Alert if customer owes money", domain: "POS & Sales" },
  { id: 47, name: "IMEI History Lookup", description: "See last sale of a serial", domain: "POS & Sales" },
  { id: 48, name: "Thermal Printer Selection", description: "Toggle 58mm / 80mm width", domain: "POS & Sales" },
  { id: 49, name: "Manual Receipt Entry", description: "Migrate legacy paper sales", domain: "POS & Sales" },
  { id: 50, name: "Sales Return to Wallet", description: "Refund to store credit only", domain: "POS & Sales" },
  { id: 51, name: "POS Session Lock", description: "Lock screen without logout", domain: "POS & Sales" },
  { id: 52, name: "Recent Customers Tab", description: "Quick access to last 5 shoppers", domain: "POS & Sales" },
  { id: 53, name: "Category Image View", description: "Toggle list/thumbnail grid", domain: "POS & Sales" },
  { id: 54, name: "Barcode Label Print", description: "Print labels directly from POS", domain: "POS & Sales" },
  { id: 55, name: "Price Check Mode", description: "Scan item to see price (no add to cart)", domain: "POS & Sales" },
  { id: 56, name: "Staff Message Board", description: "Internal notices in POS sidebar", domain: "POS & Sales" },
  { id: 57, name: "VAT/GST Summary View", description: "Real‑time tax breakdown", domain: "POS & Sales" },
  { id: 58, name: "Internal Requisition", description: "Staff taking items for shop use", domain: "POS & Sales" },
  { id: 59, name: "Commission Split", description: "Divide commission between two staff", domain: "POS & Sales" },
  { id: 60, name: "Signature Capture", description: "For high‑value card payments", domain: "POS & Sales" },

  // Domain 2: Deep‑Tech Repair Hub (61-120)
  { id: 61, name: "Job Card Intake", description: "Capture IMEI, Color, Passcode", domain: "Repair Hub" },
  { id: 62, name: "Fault Diagnostic Tree", description: "Pre‑defined issues list", domain: "Repair Hub" },
  { id: 63, name: "Visual Damage Mapping", description: "Draw cracks/scratches on device UI", domain: "Repair Hub" },
  { id: 64, name: "Pre‑Repair Video/Photo", description: "Attach visual proof to job card", domain: "Repair Hub" },
  { id: 65, name: "Technician Bench Assignment", description: "Map job to specific staff ID", domain: "Repair Hub" },
  { id: 66, name: "SLA Countdown Timer", description: "1‑hour express repair monitor", domain: "Repair Hub" },
  { id: 67, name: "Status Pipeline", description: "Diagnosing → Parts Ordered → Fixing → QC", domain: "Repair Hub" },
  { id: 68, name: "Internal Bench Notes", description: "Private technical logs", domain: "Repair Hub" },
  { id: 69, name: "Spare Parts Auto‑Deduction", description: "Trigger inventory drop on completion", domain: "Repair Hub" },
  { id: 70, name: "Parts Request Flow", description: "Tech → Inventory notification", domain: "Repair Hub" },
  { id: 71, name: "20‑Point QC Checklist", description: "FaceID, Mic, Camera, etc.", domain: "Repair Hub" },
  { id: 72, name: "Digital Signature", description: "Customer sign on tablet", domain: "Repair Hub" },
  { id: 73, name: "Warranty Sticker Gen", description: "Print unique date‑coded stickers", domain: "Repair Hub" },
  { id: 74, name: "WhatsApp Status Bot", description: "Auto‑alert “Ready for Pickup”", domain: "Repair Hub" },
  { id: 75, name: "Used Device Buy‑Back", description: "Identity scanning, automated grading (A/B/C)", domain: "Repair Hub" },
  { id: 76, name: "IC‑Level Inventory", description: "Track chips, screws, components", domain: "Repair Hub" },
  { id: 77, name: "Loaner Device Tracker", description: "Manage phones lent to customers", domain: "Repair Hub" },
  { id: 78, name: "Estimated Pickup Calculation", description: "AI‑lite time‑to‑fix", domain: "Repair Hub" },
  { id: 79, name: "Repair Ticket QR", description: "Customer scans for live progress", domain: "Repair Hub" },
  { id: 80, name: "Mandoob Dispatch", description: "Assign driver for home pickup/delivery", domain: "Repair Hub" },
  { id: 81, name: "Technician Productivity", description: "Jobs completed vs. returns", domain: "Repair Hub" },
  { id: 82, name: "Repair Warranty Expiry", description: "Auto‑alert when warranty ends", domain: "Repair Hub" },
  { id: 83, name: "Motherboard Repair Logs", description: "Track board‑level soldering", domain: "Repair Hub" },
  { id: 84, name: "Software Flash Log", description: "Record OS versions and flashing", domain: "Repair Hub" },
  { id: 85, name: "Battery Health Record", description: "Log % before/after replacement", domain: "Repair Hub" },
  { id: 86, name: "Parts Cannibalization", description: "Track parts taken from “dead” units", domain: "Repair Hub" },
  { id: 87, name: "Refurbishment Costing", description: "(Buy Price + Parts) = new asset value", domain: "Repair Hub" },
  { id: 88, name: "Water Damage Diagnostic", description: "Specific checklist for liquid", domain: "Repair Hub" },
  { id: 89, name: "Outsourced Lab Log", description: "Track jobs sent to external specialists", domain: "Repair Hub" },
  { id: 90, name: "Job Card PDF", description: "Printable document for bench", domain: "Repair Hub" },
  { id: 91, name: "Internal Technical Wiki", description: "Searchable “How‑to” guides", domain: "Repair Hub" },
  { id: 92, name: "Tech‑Load Balancer", description: "Auto‑suggest tech with least workload", domain: "Repair Hub" },
  { id: 93, name: "Parts Margin Analyzer", description: "Profit on parts vs. labour", domain: "Repair Hub" },
  { id: 94, name: "Warranty Claim Link", description: "Tie rework to original invoice", domain: "Repair Hub" },
  { id: 95, name: "Pre‑Repair Pattern Lock", description: "UI to record customer patterns", domain: "Repair Hub" },
  { id: 96, name: "Tool Calibration Log", description: "Track maintenance of shop tools", domain: "Repair Hub" },
  { id: 97, name: "Job Status History", description: "Log every status change (date/user)", domain: "Repair Hub" },
  { id: 98, name: "SMS Readiness Alert", description: "One‑click SMS to customer", domain: "Repair Hub" },
  { id: 99, name: "Repair Bundle Discount", description: "Discount for 2+ devices", domain: "Repair Hub" },
  { id: 100, name: "Diagnostic Fee Engine", description: "Charge fee even if repair rejected", domain: "Repair Hub" },
  { id: 101, name: "Technician Login via NFC", description: "Tap card to access bench", domain: "Repair Hub" },
  { id: 102, name: "Parts Backorder List", description: "Alert when requested part arrives", domain: "Repair Hub" },
  { id: 103, name: "IMEI Verification API", description: "Check blacklist during intake", domain: "Repair Hub" },
  { id: 104, name: "Internal Spare Parts Request", description: "Approval flow for expensive screens", domain: "Repair Hub" },
  { id: 105, name: "Labour Commission Engine", description: "Calculate % of labour for tech", domain: "Repair Hub" },
  { id: 106, name: "Service Area Manager", description: "Group repairs by branch/department", domain: "Repair Hub" },
  { id: 107, name: "Job Priority Toggle", description: "Mark as “VIP” or “Urgent”", domain: "Repair Hub" },
  { id: 108, name: "Post‑Repair Survey", description: "Auto‑send “How was your repair?”", domain: "Repair Hub" },
  { id: 109, name: "Digital Repair Agreement", description: "Mandatory T&Cs check", domain: "Repair Hub" },
  { id: 110, name: "Device Archive", description: "Move old repair data to cold storage", domain: "Repair Hub" },
  { id: 111, name: "Repair Category Manager", description: "Custom categories (Display, Audio, Power)", domain: "Repair Hub" },
  { id: 112, name: "Status Color Mapping", description: "Custom UI colours per status", domain: "Repair Hub" },
  { id: 113, name: "Auto‑Assign Rules", description: "e.g., all Samsung repairs to Technician A", domain: "Repair Hub" },
  { id: 114, name: "Customer Device Gallery", description: "Cloud storage for device photos", domain: "Repair Hub" },
  { id: 115, name: "Repair Cost Estimator", description: "Quick‑quote tool for phone queries", domain: "Repair Hub" },
  { id: 116, name: "Job Expiry Alert", description: "Notify manager if not picked up in 30 days", domain: "Repair Hub" },
  { id: 117, name: "Bench Queue TV", description: "Dashboard for techs to see upcoming jobs", domain: "Repair Hub" },
  { id: 118, name: "Component Serial Tracking", description: "Log serial of new screen", domain: "Repair Hub" },
  { id: 119, name: "Repair Cancellation Flow", description: "Restock parts if job cancelled", domain: "Repair Hub" },
  { id: 120, name: "Job Card Barcode", description: "Scan job card to open dashboard", domain: "Repair Hub" },

  // Domain 3: Inventory & Supply Chain (121-180)
  { id: 121, name: "Multi‑Store Matrix View", description: "Real‑time stock across all branches", domain: "Inventory" },
  { id: 122, name: "Inter‑Store Transfer Request", description: "Formal request flow between managers", domain: "Inventory" },
  { id: 123, name: "In‑Transit Tracking", description: "Status of moving stock", domain: "Inventory" },
  { id: 124, name: "Transfer Approval Workflow", description: "Request → Ship → Receive chain", domain: "Inventory" },
  { id: 125, name: "Low Stock Dashboard", description: "Visual triggers for critical items", domain: "Inventory" },
  { id: 126, name: "Predictive Re‑order Alerts", description: "Suggestions based on 30‑day sales velocity", domain: "Inventory" },
  { id: 127, name: "Purchase Order (PO) Drafting", description: "Professional orders to vendors", domain: "Inventory" },
  { id: 128, name: "Landed Cost Calculator", description: "Add Customs/Shipping/Mandoob fees", domain: "Inventory" },
  { id: 129, name: "Supplier RMA Tracking", description: "Defective parts sent back for credit", domain: "Inventory" },
  { id: 130, name: "“Blind” Stock Counting", description: "Staff count without system totals", domain: "Inventory" },
  { id: 131, name: "Full IMEI Lifecycle", description: "Chronological log from PO to sale", domain: "Inventory" },
  { id: 132, name: "Manual Stock Adjustment", description: "Correct breakage with “Reason Logs”", domain: "Inventory" },
  { id: 133, name: "Product Variants", description: "Parent‑Child for Colour/Storage/Region", domain: "Inventory" },
  { id: 134, name: "Nested Categories", description: "Phones > Apple > Used", domain: "Inventory" },
  { id: 135, name: "Barcode Generator", description: "Create unique tags for accessories", domain: "Inventory" },
  { id: 136, name: "Shelf/Bin Mapping", description: "Know exactly where the part is", domain: "Inventory" },
  { id: 137, name: "Bulk CSV Import", description: "Mass‑upload 1,000+ items", domain: "Inventory" },
  { id: 138, name: "Bulk Price Updater", description: "Mass price change by % or brand", domain: "Inventory" },
  { id: 139, name: "Mass Label Print", description: "Print stickers from a PO scan", domain: "Inventory" },
  { id: 140, name: "Ghost Stock Reserve", description: "Hold stock for online/pre‑orders", domain: "Inventory" },
  { id: 141, name: "Inventory Valuation", description: "FIFO‑based asset value reporting", domain: "Inventory" },
  { id: 142, name: "Supplier Debt Ledger", description: "Track what you owe vendors", domain: "Inventory" },
  { id: 143, name: "Ageing Report", description: "Identify stock older than 120 days", domain: "Inventory" },
  { id: 144, name: "Consignment Tracker", description: "Manage vendor‑owned inventory", domain: "Inventory" },
  { id: 145, name: "Negative Stock Block", description: "Prevent sales of missing items", domain: "Inventory" },
  { id: 146, name: "Category Tax Override", description: "Different VAT for repairs vs phones", domain: "Inventory" },
  { id: 147, name: "Supplier Credit Notes", description: "Manage money owed back to you", domain: "Inventory" },
  { id: 148, name: "Batch/Lot Tracking", description: "For batteries with expiry dates", domain: "Inventory" },
  { id: 149, name: "Internal Consumption", description: "Log parts used for shop demos", domain: "Inventory" },
  { id: 150, name: "Warehouse Heat‑Map", description: "Identify fast‑moving bins", domain: "Inventory" },
  { id: 151, name: "Multi‑Currency Buying", description: "Buy in USD/INR, sell in KD", domain: "Inventory" },
  { id: 152, name: "QR Code Shelf Tags", description: "Customer scans shelf for reviews", domain: "Inventory" },
  { id: 153, name: "Re‑order Intelligence", description: "Auto‑adjust stock triggers", domain: "Inventory" },
  { id: 154, name: "Shipping Manifests", description: "Documents for store transfers", domain: "Inventory" },
  { id: 155, name: "Weight‑Based Shipping", description: "Delivery fee calculation", domain: "Inventory" },
  { id: 156, name: "Hazardous Material Tag", description: "Label batteries for safety", domain: "Inventory" },
  { id: 157, name: "Supplier Lead‑Time", description: "Measure vendor shipping speed", domain: "Inventory" },
  { id: 158, name: "Asset Depreciation", description: "Track value drop of demo units", domain: "Inventory" },
  { id: 159, name: "Auto‑SKU Generation", description: "Brand/Model/Color logic", domain: "Inventory" },
  { id: 160, name: "Inventory Reservation", description: "Hold stock for 24‑hour quote", domain: "Inventory" },
  { id: 161, name: "Stock Turn Ratio", description: "Analytics on inventory speed", domain: "Inventory" },
  { id: 162, name: "Warehouse Pick‑List", description: "Optimised route for gathering", domain: "Inventory" },
  { id: 163, name: "Cycle Counting", description: "Daily mini‑audits for high‑value items", domain: "Inventory" },
  { id: 164, name: "Incoming QC", description: "Mandatory inspection of new shipments", domain: "Inventory" },
  { id: 165, name: "Supplier Portal", description: "Restricted view for vendors", domain: "Inventory" },
  { id: 166, name: "Dead Stock Alert", description: "Notification for zero‑sales items", domain: "Inventory" },
  { id: 167, name: "Serialized Accessories", description: "Track serials for chargers/watches", domain: "Inventory" },
  { id: 168, name: "Stock In/Out History", description: "Granular log of every movement", domain: "Inventory" },
  { id: 169, name: "Pre‑Order Management", description: "Track stock not yet in warehouse", domain: "Inventory" },
  { id: 170, name: "Supplier Category Map", description: "Which vendor sells which brands", domain: "Inventory" },
  { id: 171, name: "Bulk Transfer Approval", description: "Accept 50 items with one click", domain: "Inventory" },
  { id: 172, name: "Stock Valuation by Store", description: "Compare branch asset values", domain: "Inventory" },
  { id: 173, name: "Unit of Measure (UOM)", description: "Pieces vs Boxes vs Meters", domain: "Inventory" },
  { id: 174, name: "Supplier Bank Details", description: "Stored for wire transfers", domain: "Inventory" },
  { id: 175, name: "Defective Return Pool", description: "Bucket for parts removed from repairs", domain: "Inventory" },
  { id: 176, name: "In‑Transit Insurance Tag", description: "Mark high‑value transfers", domain: "Inventory" },
  { id: 177, name: "Shelf Life Tracker", description: "For glues and chemicals", domain: "Inventory" },
  { id: 178, name: "Auto‑Replenish", description: "Auto‑PO when stock hits zero", domain: "Inventory" },
  { id: 179, name: "Transfer Manifest QR", description: "Driver scans to mark “Arrived”", domain: "Inventory" },
  { id: 180, name: "Inventory Snapshot", description: "Export stock levels for accounting", domain: "Inventory" },

  // Domain 4: Governance, Security & HR (181-240)
  { id: 181, name: "Master Audit Trail", description: "Chronological log of every click/edit", domain: "Governance & HR" },
  { id: 182, name: "Price Edit History", description: "Track who changed a price and why", domain: "Governance & HR" },
  { id: 183, name: "Void/Delete Audit", description: "Detailed report on cancelled transactions", domain: "Governance & HR" },
  { id: 184, name: "Role‑Based Sidebar Filtering", description: "Dynamically hide features by permission", domain: "Governance & HR" },
  { id: 185, name: "Feature Toggle Board", description: "Super Admin switches for all 300 features", domain: "Governance & HR" },
  { id: 186, name: "IP Whitelisting", description: "Restrict admin access to shop Wi‑Fi", domain: "Governance & HR" },
  { id: 187, name: "Geofencing Login", description: "Staff only log in while at GPS location", domain: "Governance & HR" },
  { id: 188, name: "Staff Attendance", description: "Clock‑in/out with location verification", domain: "Governance & HR" },
  { id: 189, name: "Automated Commission Math", description: "Sales + Repair bonuses per employee", domain: "Governance & HR" },
  { id: 190, name: "Daily Z‑Report", description: "Final financial end‑of‑day summary", domain: "Governance & HR" },
  { id: 191, name: "Mid‑Shift X‑Report", description: "Snapshot without closing", domain: "Governance & HR" },
  { id: 192, name: "Profit & Loss Dashboard", description: "Daily/Monthly gross margin view", domain: "Governance & HR" },
  { id: 193, name: "Expense Tracker", description: "Log Rent/Tea/Utilities/Mandoob fees", domain: "Governance & HR" },
  { id: 194, name: "VAT/Tax Export", description: "Government‑ready CSV for filing", domain: "Governance & HR" },
  { id: 195, name: "Role Template Creator", description: "Presets for “Cashier”, “Manager”, etc.", domain: "Governance & HR" },
  { id: 196, name: "Staff Permission Override", description: "Give one specific user extra power", domain: "Governance & HR" },
  { id: 197, name: "Payroll Engine", description: "Base + commission – penalties", domain: "Governance & HR" },
  { id: 198, name: "Employee Performance Score", description: "Combined sales/repair metrics", domain: "Governance & HR" },
  { id: 199, name: "Store Profile Manager", description: "Logos, addresses, branch links", domain: "Governance & HR" },
  { id: 200, name: "Database Health Monitor", description: "Real‑time latency and uptime view", domain: "Governance & HR" },
  { id: 201, name: "Auto‑Backups", description: "Daily cloud snapshots of entire DB", domain: "Governance & HR" },
  { id: 202, name: "Remote Session Logout", description: "Admin kill any suspicious session", domain: "Governance & HR" },
  { id: 203, name: "Multi‑Store Comparison", description: "Benchmark Store A vs. Store B", domain: "Governance & HR" },
  { id: 204, name: "Aged Debt Report", description: "Identify customers who owe credit", domain: "Governance & HR" },
  { id: 205, name: "Fraud Detection Logic", description: "Flag same IMEI sold twice", domain: "Governance & HR" },
  { id: 206, name: "Discount Capping", description: "Hard‑block any discount > X%", domain: "Governance & HR" },
  { id: 207, name: "Expense Receipt Upload", description: "Photo attachments for petty cash", domain: "Governance & HR" },
  { id: 208, name: "User Activity Timeline", description: "Visual feed of staff actions", domain: "Governance & HR" },
  { id: 209, name: "Security Policy Enforcer", description: "Password expiry and complexity rules", domain: "Governance & HR" },
  { id: 210, name: "Custom Field Builder", description: "Add extra data fields to items/users", domain: "Governance & HR" },
  { id: 211, name: "System Event Notifications", description: "Email/SMS for big sales or stockouts", domain: "Governance & HR" },
  { id: 212, name: "Multi‑User Concurrency", description: "Handle 5 people editing one job", domain: "Governance & HR" },
  { id: 213, name: "God‑Mode Parity", description: "Co‑owner role with full power", domain: "Governance & HR" },
  { id: 214, name: "Regional Scoping", description: "Managers see only their shops", domain: "Governance & HR" },
  { id: 215, name: "Audit Log Encryption", description: "Make logs non‑editable even for Admins", domain: "Governance & HR" },
  { id: 216, name: "Staff Feedback Loop", description: "Internal “Suggest a Feature” tool", domain: "Governance & HR" },
  { id: 217, name: "Access Logs", description: "Track every login attempt and IP", domain: "Governance & HR" },
  { id: 218, name: "Global Search Palette", description: "Ctrl+K to jump to any feature", domain: "Governance & HR" },
  { id: 219, name: "Dark/Light Mode Theme", description: "Global UI styling engine", domain: "Governance & HR" },
  { id: 220, name: "Print Layout Builder", description: "Drag‑and‑drop receipt customizer", domain: "Governance & HR" },
  { id: 221, name: "Voucher Validation", description: "Scan physical flyers for coupons", domain: "Governance & HR" },
  { id: 222, name: "Customer Merging", description: "Clean duplicate profiles", domain: "Governance & HR" },
  { id: 223, name: "Global Heatmap", description: "Map of where customers live", domain: "Governance & HR" },
  { id: 224, name: "Tax Compliance Check", description: "Auto‑check for missing tax info", domain: "Governance & HR" },
  { id: 225, name: "User Profile Image", description: "Identify staff by photo in logs", domain: "Governance & HR" },
  { id: 226, name: "Shift Handover Note", description: "Digital report for next manager", domain: "Governance & HR" },
  { id: 227, name: "Training Mode", description: "Sandbox for new hires (no real data)", domain: "Governance & HR" },
  { id: 228, name: "Feature Adoption Score", description: "Show which staff use which tools", domain: "Governance & HR" },
  { id: 229, name: "Legal Agreement Manager", description: "Terms & Conditions versioning", domain: "Governance & HR" },
  { id: 230, name: "Currency Exchange Rate", description: "Auto‑update USD/INR to KD", domain: "Governance & HR" },
  { id: 231, name: "GDPR/Privacy Tools", description: "Export/Delete customer data", domain: "Governance & HR" },
  { id: 232, name: "System Health Check", description: "One‑click check of all API endpoints", domain: "Governance & HR" },
  { id: 233, name: "Bulk User Invite", description: "Onboard 50 staff via CSV", domain: "Governance & HR" },
  { id: 234, name: "Department Hierarchy", description: "Manage sub‑teams (Sales, Tech, HR)", domain: "Governance & HR" },
  { id: 235, name: "Maintenance Mode Toggle", description: "Lock app for updates", domain: "Governance & HR" },
  { id: 236, name: "API Key Management", description: "For external integrations", domain: "Governance & HR" },
  { id: 237, name: "Payment Terminal Setup", description: "Configure card machine links", domain: "Governance & HR" },
  { id: 238, name: "Webhook Manager", description: "Send data to external URLs", domain: "Governance & HR" },
  { id: 239, name: "Report Scheduler", description: "Email Z‑report at 11 PM daily", domain: "Governance & HR" },
  { id: 240, name: "Dashboard Widget Customizer", description: "Staff pin favourite tools", domain: "Governance & HR" },

  // Domain 5: Omnichannel, CRM & IoT (241-300)
  { id: 241, name: "BOPIS Dashboard", description: "Buy Online, Pick Up In‑Store fulfillment", domain: "Omnichannel & CRM" },
  { id: 242, name: "Inventory Ghosting", description: "Reserve stock exclusively for web", domain: "Omnichannel & CRM" },
  { id: 243, name: "Price Syncing Engine", description: "Sync POS prices with Shopify/Woo", domain: "Omnichannel & CRM" },
  { id: 244, name: "Anomaly Detection", description: "Flag suspicious deletions or edits", domain: "Omnichannel & CRM" },
  { id: 245, name: "WhatsApp Support Bot", description: "Auto‑answer repair status queries", domain: "Omnichannel & CRM" },
  { id: 246, name: "Biometric Staff Login", description: "WebAuthn/Fingerprint integration", domain: "Omnichannel & CRM" },
  { id: 247, name: "Customer Queue Display", description: "TV integration for repair waitlists", domain: "Omnichannel & CRM" },
  { id: 248, name: "Remote Diagnostic Hook", description: "Tools for software‑based remote repair", domain: "Omnichannel & CRM" },
  { id: 249, name: "Loyalty Multiplier Events", description: "“Double Points” weekend logic", domain: "Omnichannel & CRM" },
  { id: 250, name: "Global Analytics Heatmap", description: "Map showing customer density", domain: "Omnichannel & CRM" },
  { id: 251, name: "WhatsApp API Config", description: "Set up templates for receipts", domain: "Omnichannel & CRM" },
  { id: 252, name: "Customer Tiering", description: "Auto‑label (Silver, Gold, VIP)", domain: "Omnichannel & CRM" },
  { id: 253, name: "Birthday Coupon Bot", description: "Automated SMS/WhatsApp for birthdays", domain: "Omnichannel & CRM" },
  { id: 254, name: "Review Solicitor", description: "SMS link for Google Review after delivery", domain: "Omnichannel & CRM" },
  { id: 255, name: "Mandoob Tracker", description: "Real‑time driver location for delivery", domain: "Omnichannel & CRM" },
  { id: 256, name: "Customer 360 Profile", description: "Full history, spend, repair logs", domain: "Omnichannel & CRM" },
  { id: 257, name: "Blacklist Manager", description: "Flag problematic customers", domain: "Omnichannel & CRM" },
  { id: 258, name: "Self‑Service Portal", description: "Online status check via Ticket ID", domain: "Omnichannel & CRM" },
  { id: 259, name: "Omnichannel Search", description: "Find online orders in POS", domain: "Omnichannel & CRM" },
  { id: 260, name: "Click‑to‑Call", description: "Integrated dialing from CRM", domain: "Omnichannel & CRM" },
  { id: 261, name: "Social Media Linkage", description: "Attach Instagram/TikTok handles", domain: "Omnichannel & CRM" },
  { id: 262, name: "Waitlist Logic", description: "Notify when a part arrives", domain: "Omnichannel & CRM" },
  { id: 263, name: "Pre‑order Management", description: "Deposits for unreleased phones", domain: "Omnichannel & CRM" },
  { id: 264, name: "Family Account Linking", description: "Share points across family members", domain: "Omnichannel & CRM" },
  { id: 265, name: "Geo‑Fencing Alerts", description: "Notify shop when driver is near", domain: "Omnichannel & CRM" },
  { id: 266, name: "Integrated Map", description: "Show addresses for delivery routing", domain: "Omnichannel & CRM" },
  { id: 267, name: "Customer CLV", description: "Predict long‑term profit per user", domain: "Omnichannel & CRM" },
  { id: 268, name: "Chat History Archive", description: "Save all WhatsApp conversations", domain: "Omnichannel & CRM" },
  { id: 269, name: "Store Feedback Screen", description: "“Rate us” tablet at exit", domain: "Omnichannel & CRM" },
  { id: 270, name: "Incident Log", description: "Record customer complaints or accidents", domain: "Omnichannel & CRM" },
  { id: 271, name: "Voucher Validation", description: "Scan physical flyers", domain: "Omnichannel & CRM" },
  { id: 272, name: "Excel/CSV Export", description: "Turn any list into spreadsheet", domain: "Omnichannel & CRM" },
  { id: 273, name: "Security Policy", description: "Enforce password changes every 90 days", domain: "Omnichannel & CRM" },
  { id: 274, name: "Staff Messenger", description: "Internal chat for team coordination", domain: "Omnichannel & CRM" },
  { id: 275, name: "IoT Scale Sync", description: "For weighing parts or devices", domain: "Omnichannel & CRM" },
  { id: 276, name: "Smart Display Screen", description: "Customer monitor via WebSockets", domain: "Omnichannel & CRM" },
  { id: 277, name: "RFID Tag Reader", description: "Identify devices on bench pad", domain: "Omnichannel & CRM" },
  { id: 278, name: "IoT Printer Status", description: "Alert POS if paper is low", domain: "Omnichannel & CRM" },
  { id: 279, name: "Cash Drawer Log", description: "Record every physical opening", domain: "Omnichannel & CRM" },
  { id: 280, name: "Kiosk Mode", description: "Self‑service UI for accessory sales", domain: "Omnichannel & CRM" },
  { id: 281, name: "Audio Announcements", description: "“Job Assigned to Ahmed” over speakers", domain: "Omnichannel & CRM" },
  { id: 282, name: "Digital Signage Sync", description: "Display promos on store TVs", domain: "Omnichannel & CRM" },
  { id: 283, name: "Payment Terminal Handshake", description: "Direct tap‑to‑POS integration", domain: "Omnichannel & CRM" },
  { id: 284, name: "Door Sensor Log", description: "Track shop foot traffic", domain: "Omnichannel & CRM" },
  { id: 285, name: "Inventory Pick‑List QR", description: "Scan to confirm item is picked", domain: "Omnichannel & CRM" },
  { id: 286, name: "Batch IMEI Registration", description: "Add 500 serials via CSV", domain: "Omnichannel & CRM" },
  { id: 287, name: "Web‑to‑Store Fulfill", description: "Push web orders to nearest shop", domain: "Omnichannel & CRM" },
  { id: 288, name: "Automatic Stock Reconciliation", description: "Suggest fixes for counts", domain: "Omnichannel & CRM" },
  { id: 289, name: "Supplier Order Reminder", description: "Automated emails for late POs", domain: "Omnichannel & CRM" },
  { id: 290, name: "Duplicate Customer Merge", description: "One‑click cleanup of same mobiles", domain: "Omnichannel & CRM" },
  { id: 291, name: "Failed Payment Retry", description: "System re‑queue for card errors", domain: "Omnichannel & CRM" },
  { id: 292, name: "Auto‑Assign Tech", description: "Lightest workload logic", domain: "Omnichannel & CRM" },
  { id: 293, name: "Executive Summary Email", description: "Daily digest for owner", domain: "Omnichannel & CRM" },
  { id: 294, name: "Product Affinity Analysis", description: "“People who bought X also bought Y”", domain: "Omnichannel & CRM" },
  { id: 295, name: "Return Rate by SKU", description: "Identify bad batches of phones", domain: "Omnichannel & CRM" },
  { id: 296, name: "Sales Funnel Analytics", description: "View → Cart → Pay tracking", domain: "Omnichannel & CRM" },
  { id: 297, name: "Zero‑Stock Impact", description: "Report lost sales due to stockouts", domain: "Omnichannel & CRM" },
  { id: 298, name: "Privacy Anonymization", description: "Clean data for audit exports", domain: "Omnichannel & CRM" },
  { id: 299, name: "Tamper‑Proof Audit", description: "Append‑only log files", domain: "Omnichannel & CRM" },
  { id: 300, name: "Global Search Palette", description: "Ctrl+K rapid navigation engine", domain: "Omnichannel & CRM" },
];
